SELECT ?subcollection
WHERE {
 {?subcollection <fedora-rels-ext:isMemberOf> ?collection}
 UNION
 {?subcollection <fedora-rels-ext:isMemberOfCollection> ?collection}
 ?subcollection <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
}
