<?php
/**
 * @file
 * @author: William Panting
 * @date: 17/05/2011
 * This module is intended to implement a generic Islandora workflow around the creation and publication of objects.
 */

/**
 * This generates the main workflow page
 * @return $page: The html of the page to return
 */
function islandora_workflow_work() {
  $page='';
  $page=$page ."<p>HelloWorld1</p>";
  return $page;
}

/**
 * This generates the page for editing collection level permissions
 * @return $page: The html of the page to return
 */
function islandora_workflow_collection_permissions() {
  module_load_include('inc', 'islandora_workflow', 'islandora_workflow');
  
  
  $page='';  
  $collections=get_all_collections();
  foreach ($collections as $collection_pid => $collection_label) {
    $page=$page . $collection_pid . $collection_label;
  }
  $page=$page.'<br/>';
  dsm($collections);
  dsm(islandora_workflow_get_roles_with_module_permissions());
  
  return $page;
}

/**
 * The menu entries for this module.
 * @return $menuEntries: An arrray of the items to be added to the drupal menu
 */
function islandora_workflow_menu() {
  $menuEntries= array();
  //settings associated with islandora_workflow
  $menuEntries['admin/settings/islandora_workflow_opts']=array(
    'title' => t('Islandora workflow settings'),
    'description' => t('Here you can change various settings for the islandora_workflow module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_workflow_admin'),
    'access arguments' => array('islandora_workflow_Administrator'),
    'type' => MENU_NORMAL_ITEM
  );
    //settings associated with islandora_workflow and collection permissions
  $menuEntries['admin/settings/islandora_workflow_perms']=array(
    'title' => t('Islandora workflow permissions'),
    'description' => t('Here you can assign permissions to roles on a collection by collection level.'),
    'page callback' => 'islandora_workflow_collection_permissions',
    'access callback' => 'islandora_wokflow_check_permissions',
    'access arguments' => array('islandora_workflow_Administrator', 'islandora_workflow_Manager'),
    'type' => MENU_NORMAL_ITEM
  );
  //main working page for islandora_workflow
  $menuEntries['islandora_workflow']=array(
    'title' => t('My Islandora work'),
    'description' => t('This is the main access point to islandora_workflow'),
    'page callback' => 'islandora_workflow_work',
    'access callback' => 'islandora_wokflow_check_permissions',
    'access arguments' => array('islandora_workflow_Administrator', 'islandora_workflow_Editor', 'islandora_workflow_Manager', 'islandora_workflow_Submitter'),
    'type' => MENU_NORMAL_ITEM
   );
 return $menuEntries;
}

/**
 * This function is the access callback used for access to the workflow section of this module
 * @param $permission_array: those user roles to allow access
 * @return $bool: wheather or not to permit access
 */
function islandora_wokflow_check_permissions($permission_array) {  
  //loop through permissions allowed
  for ($i=0; $i<sizeof($permission_array);$i++) {
    //return true if the user has an allowed permission
    if (user_access($arr_perms[$i])) {
      return TRUE;
    }
  }
  //if no permission matched then return false
  return FALSE;
}

/**
 * This function returns the form that will let an administrator modify the module's settings
 * @return $adminForm: the form for edditing islandora_workflow settings.
 */
function islandora_workflow_admin() {
  $adminForm=array();
  //security setting ie. xacml enforced on/off
  $adminForm['islandora_workflow_enforce_security']= array(
    '#type' => 'checkbox',
    '#title' => t('Enforce Security'),
    '#default_value' => variable_get('islandora_workflow_enforce_security', 0),
    '#description' => t("Wheather or not to use XACML to enforce workflow."),
  ); 
  return system_settings_form($adminForm); 
}

/**
 * drupal permission hook
 * The list of avaialble permissions for this module.
 * @return array: The list of permissions.
 */
function islandora_workflow_perm() {
  return array('islandora_workflow_Administrator', 'islandora_workflow_Editor', 'islandora_workflow_Manager', 'islandora_workflow_Submitter');
}

/**
 * drupal hook to show help
 * @param $path: The path that the help is being accessed from.
 * @return $help: The help string that will be returned to the user.
 */
function islandora_workflow_help($path, $arg) {
  $help='';//default
  
  switch ($path) {
    case 'admin/modules#description' :
    $help= t('A generic workflow module for Fedora objects.');
  }
  
  return $help;
}

/**
 * This function registers themeing functions with Drupal.
 * @return array $theme_functions: the array of theme functions
 */
function islandora_workflow_theme() {
   $theme_functions=array();
   
    $theme_functions['islandora_workflow_collection_permissions_themeing'] = array(
       'arguments' => array(
       'form' => NULL));
    
   return $theme_functions;
 }
 
 /**
  * This function provides the necessary themeing for the collection permission page
  * @return $output: The rendered table/form
  */
function islandora_workflow_collection_permissions_themeing() {
  $output='';
  
  return $output;
}