<?php
/**
 * @author: William Panting
 * @date: 17/05/2011
 */
function IslandoraWorkflow_admin() {
  return "";
}

function IslandoraWorkflow_admin_settings_submit($form, $form_values) {
  
}

/**
 * drupal menu hook
 */
function IslandoraWorkflow_menu() {
 return "";
}

/**
 * drupal hook to show help
 */
function IslandoraWorkflow_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description' :
      return t('A generic workflow module for Fedora objects.');
    case 'node/add#fedora_repository' :
      return t('');
  }
}